from django.contrib import admin

from desenvolvimento.models import *


admin.site.register(DepartamentoAcademico)
admin.site.register(Professor)
admin.site.register(Curso)
admin.site.register(Coordenacao)
admin.site.register(Artigo)
admin.site.register(ArtigoEmPeriodico)
admin.site.register(ArtigoEmConferencia)
admin.site.register(Projeto)
admin.site.register(Evento)
admin.site.register(AreaDeAtuacao)
admin.site.register(Integrante)
admin.site.register(IntegranteProfessor)
admin.site.register(DadosDeProfessor)
admin.site.register(Disciplina)
admin.site.register(RelacaoDisciplinaCurso)
admin.site.register(Matriz)
admin.site.register(PlanoDeAula)
admin.site.register(DiaDaSemana)
admin.site.register(HorarioDaAula)
admin.site.register(Oferecimento)
admin.site.register(Comissao)
admin.site.register(Colegiado)
admin.site.register(Aluno)
# admin.site.register(Estagiario)
admin.site.register(MembroEleito)
admin.site.register(NDE)
admin.site.register(RelacaoDiaDaSemanaHorarioDeAula)
admin.site.register(EmpresaJunior)
admin.site.register(CentroAcademico)
admin.site.register(CalendarioAcademico)
admin.site.register(InfraEstrutura)
admin.site.register(Sala)